import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Alnur Khan Missiom',
      email: 'alnurkhanmissiom@gmail.com',
      password: bcrypt.hashSync('Alnur373@$'),
      isAdimin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdimin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free shirt',
      catagory: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 25,
      rating: 4.5,
      brand: 'Nike',
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      catagory: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 30,
      rating: 3.2,
      brand: 'Adidas',
      numReviews: 10,
      countInStock: 5,
      description: 'A popular Shirt',
    },
    {
      name: 'Free Shirt',
      slug: 'slim-shirt',
      catagory: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 35,
      rating: 4.5,
      brand: 'Rymond',
      numReviews: 8,
      countInStock: 2,
      description: 'A popular Shirt',
    },
    {
      name: 'Rare Shirt',
      slug: 'rare-shirt',
      catagory: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 30,
      rating: 4.5,
      brand: 'Rymond',
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'Golf-Pants',
      catagory: 'Shirts',
      image: '/images/pants1.jpg',
      price: 70,
      rating: 4.5,
      brand: 'Oliver',
      numReviews: 8,
      countInStock: 2,
      description: 'Smart Looking Pants',
    },
    {
      name: 'Golf Pants',
      slug: 'fit-Pants',
      catagory: 'Shirts',
      image: '/images/pants2.jpg',
      price: 25,
      rating: 4.5,
      brand: 'zara',
      numReviews: 8,
      countInStock: 20,
      description: 'Smart Looking Pants',
    },
    {
      name: 'Golf Pants',
      slug: 'Classic-Pants',
      catagory: 'Shirts',
      image: '/images/pants3.jpg',
      price: 30,
      rating: 4.5,
      brand: 'Oliver',
      numReviews: 8,
      countInStock: 20,
      description: 'Smart Looking Pants',
    },
    {
      name: 'Golf Pants',
      slug: 'rare-Pants',
      catagory: 'Shirts',
      image: '/images/pants3.jpg',
      price: 30,
      rating: 4.5,
      brand: 'Oliver',
      numReviews: 8,
      countInStock: 20,
      description: 'Smart Looking Pants',
    },
  ],
};
export default data;
